# Generated by Django 2.2.6 on 2020-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
        ),
    ]
