# Generated by Django 2.2.6 on 2020-04-02 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trainers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MONDAY', 'Понедельник'), ('TUESDAY', 'Вторник'), ('WEDNESDAY', 'Среда'), ('THURSDAY', 'Четверг'), ('FRIDAY', 'Пятница'), ('SATURDAY', 'Суббота'), ('SUNDAY', 'Воскресенье')], max_length=15)),
                ('time', models.TimeField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('clients', models.ManyToManyField(to='clients.Client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trainers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.Workout')),
            ],
        ),
    ]
